# Changes here will be overwritten by Copier
_commit: ae0e517
_src_path: gh:34j/pypackage-template-fork
add_me_as_contributor: false
copyright_year: '2023'
documentation: true
email: 34j.95a2p@simplelogin.com
full_name: 34j
github_username: 34j
initial_commit: false
open_source_license: CC0 1.0 Universal
open_with_vscode: false
package_name: pdfdecrypt
project_name: pdfdecrypt
project_short_description: Simple package for decrypting PDF files
project_slug: pdfdecrypt
run_poetry_install: false
setup_github: false
setup_pre_commit: false
setup_venv: false
venv_version: '3.10'

