# Changes here will be overwritten by Copier
_commit: ae0e517
_src_path: gh:34j/pypackage-template-fork
add_me_as_contributor: true
copyright_year: '2023'
documentation: true
email: 34j.95a2p@simplelogin.com
full_name: 34j
github_username: 34j
initial_commit: true
open_source_license: CC0 1.0 Universal
open_with_vscode: true
package_name: pdfdecrypt
project_name: pdfdecrypt
project_short_description: Simple package for decrypting PDF files
project_slug: pdfdecrypt
run_poetry_install: true
setup_github: true
setup_pre_commit: true
setup_venv: true
venv_version: '3.10'

